package Vista;

import Controlador.Controlador;
import Modelo.CerrarCaja;
import Modelo.MetodosEmpleados;
import Modelo.Pedido;
import Modelo.UtilidadesTablas;
import java.util.List;
import javax.swing.JOptionPane;

public class IngresarPedido extends javax.swing.JPanel {

    public IngresarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        InputCantidad = new javax.swing.JTextField();
        BtnListo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        InputFilaNo = new javax.swing.JTextField();
        btnEspera = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        boxMesaPedido = new javax.swing.JComboBox<>();
        boxCategor = new javax.swing.JComboBox<>();
        boxPedido = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        boxMesero = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedido = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1557, 908));
        setMinimumSize(new java.awt.Dimension(1557, 908));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(1557, 908));
        jPanel3.setMinimumSize(new java.awt.Dimension(1557, 908));
        jPanel3.setPreferredSize(new java.awt.Dimension(1557, 908));

        jLabel2.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(54, 61, 68));
        jLabel2.setText("INGRESAR PEDIDOS");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(54, 61, 68));
        jLabel1.setText("Categoría");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(54, 61, 68));
        jLabel5.setText("Cantidad");

        InputCantidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        InputCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCantidadActionPerformed(evt);
            }
        });

        BtnListo.setBackground(new java.awt.Color(255, 102, 102));
        BtnListo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BtnListo.setForeground(new java.awt.Color(255, 255, 255));
        BtnListo.setText("Pedido listo");
        BtnListo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 204));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(54, 61, 68));
        jLabel7.setText("No. Fila");

        InputFilaNo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        InputFilaNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputFilaNoActionPerformed(evt);
            }
        });

        btnEspera.setBackground(new java.awt.Color(104, 131, 161));
        btnEspera.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnEspera.setForeground(new java.awt.Color(255, 255, 255));
        btnEspera.setText("Agregar a cola");
        btnEspera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsperaActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(54, 61, 68));
        jLabel4.setText("Mesero");

        jLabel8.setBackground(new java.awt.Color(255, 204, 204));
        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(54, 61, 68));
        jLabel8.setText("Mesa");

        boxMesaPedido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        boxMesaPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Mesa...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        boxCategor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        boxCategor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione categoría...", "Platos", "Bebidas" }));
        boxCategor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCategorActionPerformed(evt);
            }
        });

        boxPedido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        boxPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione pedido..." }));
        boxPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPedidoActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(54, 61, 68));
        jLabel9.setText("Pedido");

        btnSeleccionar.setBackground(new java.awt.Color(255, 102, 102));
        btnSeleccionar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        boxMesero.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        boxMesero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione mesero...", " " }));
        boxMesero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                boxMeseroFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnListo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(boxCategor, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                    .addComponent(InputCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxPedido, javax.swing.GroupLayout.Alignment.LEADING, 0, 147, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(InputFilaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(69, 69, 69)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxMesaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxCategor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InputCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxMesaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(btnEspera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(InputFilaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnListo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );

        jSeparator1.setForeground(new java.awt.Color(95, 125, 246));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/carpas (1).png"))); // NOI18N

        tablePedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mesa", "Mesero", "Pedido", "Cantidad", "Estado", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePedido);
        if (tablePedido.getColumnModel().getColumnCount() > 0) {
            tablePedido.getColumnModel().getColumn(0).setResizable(false);
            tablePedido.getColumnModel().getColumn(1).setResizable(false);
            tablePedido.getColumnModel().getColumn(2).setResizable(false);
            tablePedido.getColumnModel().getColumn(3).setResizable(false);
            tablePedido.getColumnModel().getColumn(4).setResizable(false);
            tablePedido.getColumnModel().getColumn(5).setResizable(false);
            tablePedido.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void InputCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCantidadActionPerformed

    private void BtnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListoActionPerformed

        MetodosEmpleados metodos = new MetodosEmpleados();
        String id_pedidos = InputFilaNo.getText();

        if (!id_pedidos.isEmpty()) {

            int resultado = metodos.act(id_pedidos);

            if (resultado > 0) {
                JOptionPane.showMessageDialog(null, "El estado del pedido " + id_pedidos + " ha sido actualizado.");

                Controlador c = new Controlador();

                UtilidadesTablas.tablaNormal(tablePedido);
                c.datosPedidos(tablePedido);
                // Eliminar fila de la tabla en la interfaz

                InputFilaNo.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar el estado.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese el id del pedido.");
        }


    }//GEN-LAST:event_BtnListoActionPerformed

    private void InputFilaNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputFilaNoActionPerformed

    }//GEN-LAST:event_InputFilaNoActionPerformed

    private void btnEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsperaActionPerformed
        String mesa = (String) boxMesaPedido.getSelectedItem();
            String mesero = (String) boxMesero.getSelectedItem();
            String categoria = (String) boxCategor.getSelectedItem();
            String producto = (String) boxPedido.getSelectedItem();
            String cantidad = InputCantidad.getText();

            // Verificar si la cantidad es un número
            try {
                
                // Intenta convertir la cantidad a un número entero
                int cantidadNumerica = Integer.parseInt(cantidad);

                // Si la conversión es exitosa, crea el pedido
                Pedido pedido = new Pedido();
                pedido.setMesa(mesa);
                pedido.setMesero(mesero);
                pedido.setCategoria(categoria);
                pedido.setProducto(producto);
                pedido.setCantidad(cantidad);

                // Agrega el pedido y realiza otras operaciones
                CerrarCaja.agregarPedido(pedido);
                Controlador c = new Controlador();

                if(mesa.equals("Seleccione Mesa...") || mesero.equals("Seleccione mesero...") || categoria.equals("Seleccione categoría...") || producto.equals("Seleccione pedido...") || cantidad.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor, ingrese los campos faltantes.");
                } else {
                    c.ingresarPedido(mesa, mesero, producto, cantidad, categoria, tablePedido);
                    boxMesero.setSelectedIndex(0);
                    boxPedido.setSelectedIndex(0);
                    InputCantidad.setText("");
                    boxMesaPedido.setSelectedIndex(0);
                }
            } catch (NumberFormatException e) {
                // Si la conversión falla, muestra un mensaje de error
                JOptionPane.showMessageDialog(null, "La cantidad debe ser un número válido.");
            }
    }//GEN-LAST:event_btnEsperaActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        
        String[] Bebidas = {"Sake", "Amazake", "Ramune", "Agua"};
        String[] Platos = {"Sushi", "Onigiri", "Tonkatsu", "Tempura", "Yakitori", "Okonomiyaki", "Oyakodon", "Katsudon", "Nikujaga", "Karaage"};
        boxPedido.removeAllItems();
        String categoriaSeleccionada = (String) boxCategor.getSelectedItem();
        if (categoriaSeleccionada.equals("Bebidas")) {
            for (String bebida : Bebidas) {
                boxPedido.addItem(bebida);
            }

        } else if (categoriaSeleccionada.equals("Platos")) {
            boxPedido.removeAllItems();
            for (String plato : Platos) {
                boxPedido.addItem(plato);
            }
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void boxMeseroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boxMeseroFocusGained
        // Limpiar el JComboBox

        boxMesero.removeAllItems();
        // Agregar "Seleccione mesero..." al inicio de la lista
        boxMesero.addItem("Seleccione mesero...");
        boxMesero.setSelectedIndex(0);

        MetodosEmpleados me = new MetodosEmpleados();
        // Obtener los nombres de los meseros desde la base de datos
        List<String> nombresMeseros = me.obtenerNombresMeseros();

        // Agregar los nombres de los meseros al JComboBox
        for (String nombre : nombresMeseros) {
            boxMesero.addItem(nombre);
        }
    }//GEN-LAST:event_boxMeseroFocusGained

    private void boxCategorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCategorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxCategorActionPerformed

    private void boxPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnListo;
    public javax.swing.JTextField InputCantidad;
    public javax.swing.JTextField InputFilaNo;
    public javax.swing.JComboBox<String> boxCategor;
    public javax.swing.JComboBox<String> boxMesaPedido;
    public javax.swing.JComboBox<String> boxMesero;
    public javax.swing.JComboBox<String> boxPedido;
    public javax.swing.JButton btnEspera;
    public javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable tablePedido;
    // End of variables declaration//GEN-END:variables
}
