package Vista;

import Controlador.Controlador;
import Modelo.MetodosEmpleados;
import Modelo.UtilidadesTablas;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class Menu_Cajero extends javax.swing.JFrame {
    
    private Inicio inicio;
    public Menu_Cajero(Inicio inicio) {
        this.inicio = inicio;
        initComponents();
    }
    public void mostrarC(JPanel C){
        C.setSize(1557, 920);
        C.setLocation(0, 0);

        SwingUtilities.invokeLater(() -> {
        C_content.removeAll();
        C_content.add(C, BorderLayout.CENTER);
        C_content.revalidate();
        C_content.repaint();
});
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Background1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnIngresarPedido = new javax.swing.JButton();
        btnGenerarFact = new javax.swing.JButton();
        btnRegCliente = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnAgProducto = new javax.swing.JButton();
        btnConsultarInv = new javax.swing.JButton();
        btnCrearCuenta = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnElegirMesa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        nomEmple = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        C_content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1278, 770));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setMaximumSize(new java.awt.Dimension(1278, 770));
        Background.setMinimumSize(new java.awt.Dimension(1278, 770));
        Background.setPreferredSize(new java.awt.Dimension(1278, 770));

        Background1.setBackground(new java.awt.Color(255, 255, 255));
        Background1.setMaximumSize(new java.awt.Dimension(1278, 770));
        Background1.setMinimumSize(new java.awt.Dimension(1278, 770));

        Menu.setBackground(new java.awt.Color(104, 131, 161));
        Menu.setMaximumSize(new java.awt.Dimension(365, 937));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(104, 131, 161));

        btnIngresarPedido.setBackground(new java.awt.Color(104, 131, 161));
        btnIngresarPedido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnIngresarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarPedido.setText("Ingresar pedido");
        btnIngresarPedido.setBorder(null);
        btnIngresarPedido.setBorderPainted(false);
        btnIngresarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPedidoActionPerformed(evt);
            }
        });

        btnGenerarFact.setBackground(new java.awt.Color(104, 131, 161));
        btnGenerarFact.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnGenerarFact.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarFact.setText("Generar factura");
        btnGenerarFact.setBorder(null);
        btnGenerarFact.setBorderPainted(false);
        btnGenerarFact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerarFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFactActionPerformed(evt);
            }
        });

        btnRegCliente.setBackground(new java.awt.Color(104, 131, 161));
        btnRegCliente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnRegCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegCliente.setText("Registrar cliente");
        btnRegCliente.setBorder(null);
        btnRegCliente.setBorderPainted(false);
        btnRegCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegClienteActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(104, 131, 161));

        btnAgProducto.setBackground(new java.awt.Color(104, 131, 161));
        btnAgProducto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnAgProducto.setForeground(new java.awt.Color(181, 178, 178));
        btnAgProducto.setText("Agregar producto");
        btnAgProducto.setBorder(null);
        btnAgProducto.setBorderPainted(false);
        btnAgProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgProducto.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnAgProducto.setDefaultCapable(false);
        btnAgProducto.setDoubleBuffered(true);
        btnAgProducto.setVerifyInputWhenFocusTarget(false);
        btnAgProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgProductoActionPerformed(evt);
            }
        });

        btnConsultarInv.setBackground(new java.awt.Color(104, 131, 161));
        btnConsultarInv.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnConsultarInv.setForeground(new java.awt.Color(181, 178, 178));
        btnConsultarInv.setText("Consultar inventario");
        btnConsultarInv.setBorder(null);
        btnConsultarInv.setBorderPainted(false);
        btnConsultarInv.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnConsultarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarInvActionPerformed(evt);
            }
        });

        btnCrearCuenta.setBackground(new java.awt.Color(104, 131, 161));
        btnCrearCuenta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(181, 178, 178));
        btnCrearCuenta.setText("Crear nueva cuenta");
        btnCrearCuenta.setBorder(null);
        btnCrearCuenta.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(255, 142, 164));
        btnC.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnC.setForeground(new java.awt.Color(255, 255, 255));
        btnC.setText("Cerrar sesión");
        btnC.setBorder(null);
        btnC.setBorderPainted(false);
        btnC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAgProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConsultarInv, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
            .addComponent(btnC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCrearCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnAgProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarInv, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnGenerarFact, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                        .addComponent(btnIngresarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIngresarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarFact, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 365, 470));

        btnElegirMesa.setBackground(new java.awt.Color(104, 131, 161));
        btnElegirMesa.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnElegirMesa.setForeground(new java.awt.Color(255, 255, 255));
        btnElegirMesa.setText("Elegir mesa");
        btnElegirMesa.setBorder(null);
        btnElegirMesa.setBorderPainted(false);
        btnElegirMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnElegirMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirMesaActionPerformed(evt);
            }
        });
        Menu.add(btnElegirMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 365, 52));

        jPanel1.setBackground(new java.awt.Color(104, 131, 161));

        jPanel8.setBackground(new java.awt.Color(104, 131, 161));

        jLabel5.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cajero");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/89a2966a8b8718d343391d91cc0db835-removebg-preview (2) (1) (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel5))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Menu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 290, 210));

        Header.setBackground(new java.awt.Color(167, 193, 225));

        nomEmple.setBackground(new java.awt.Color(255, 255, 255));
        nomEmple.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        nomEmple.setForeground(new java.awt.Color(255, 255, 255));
        nomEmple.setText("Hola, nombre");

        jLabel1.setFont(new java.awt.Font("Roboto Black", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 239, 238));
        jLabel1.setText("Es posible que ciertas opciones estén desactivadas debido a tus permisos o nivel de acceso.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡En estos momentos estás en CAJERO!");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nomEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap())
        );

        C_content.setBackground(new java.awt.Color(255, 255, 255));
        C_content.setMaximumSize(new java.awt.Dimension(913, 616));
        C_content.setMinimumSize(new java.awt.Dimension(913, 616));

        javax.swing.GroupLayout C_contentLayout = new javax.swing.GroupLayout(C_content);
        C_content.setLayout(C_contentLayout);
        C_contentLayout.setHorizontalGroup(
            C_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 913, Short.MAX_VALUE)
        );
        C_contentLayout.setVerticalGroup(
            C_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Background1Layout = new javax.swing.GroupLayout(Background1);
        Background1.setLayout(Background1Layout);
        Background1Layout.setHorizontalGroup(
            Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background1Layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Background1Layout.setVerticalGroup(
            Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 770, Short.MAX_VALUE)
            .addGroup(Background1Layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnElegirMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirMesaActionPerformed
           try {
            MetodosEmpleados metodos = new MetodosEmpleados();
            ingresarMesaa C1 = new ingresarMesaa();
            Controlador c = new Controlador();
            
            mostrarC(C1);
            UtilidadesTablas.tablaNormal(C1.tblMesa);
            c.listarAGGM(C1.tblMesa);
            
            metodos.registrarAccionEmpleado("elegir mesa");
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Cajero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnElegirMesaActionPerformed

    private void btnRegClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegClienteActionPerformed
        try {
            MetodosEmpleados metodos = new MetodosEmpleados();
            RegistrarCliente C3 = new RegistrarCliente();
            Controlador c = new Controlador();
            
            C3.setCaj(this);
            mostrarC(C3);
            UtilidadesTablas.tablaNormal(C3.tablacliente);
            c.listar(C3.tablacliente);
            
            metodos.registrarAccionEmpleado("registrar cliente");
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Cajero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegClienteActionPerformed

    private void btnGenerarFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFactActionPerformed
    
        try {
            MetodosEmpleados metodos = new MetodosEmpleados();
            GenerarFactura C4 = new GenerarFactura();
            mostrarC(C4);
            
            metodos.registrarAccionEmpleado("generar factura");
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Cajero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarFactActionPerformed

    private void btnIngresarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPedidoActionPerformed
        try {
            MetodosEmpleados metodos = new MetodosEmpleados();
            IngresarPedido C2 = new IngresarPedido();
            Controlador c = new Controlador();
            
            mostrarC(C2);
            UtilidadesTablas.tablaNormal(C2.tablePedido);
            c.datosPedidos(C2.tablePedido);
            
            metodos.registrarAccionEmpleado("ingresar pedido");
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Cajero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIngresarPedidoActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCActionPerformed

    private void btnAgProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgProductoActionPerformed
        JOptionPane.showMessageDialog(null, "¡Sólo para Administrador!", "Ups...", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnAgProductoActionPerformed

    private void btnConsultarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarInvActionPerformed
        JOptionPane.showMessageDialog(null, "¡Sólo para Administrador!", "Ups...", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnConsultarInvActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        JOptionPane.showMessageDialog(null, "¡Sólo para Administrador!", "Ups...", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Background1;
    public javax.swing.JPanel C_content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnAgProducto;
    public javax.swing.JButton btnC;
    private javax.swing.JButton btnConsultarInv;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnElegirMesa;
    private javax.swing.JButton btnGenerarFact;
    private javax.swing.JButton btnIngresarPedido;
    private javax.swing.JButton btnRegCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel nomEmple;
    // End of variables declaration//GEN-END:variables
}
